/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class data_scripts_ffmpeg_FFmpeg */

#ifndef _Included_data_scripts_ffmpeg_FFmpeg
#define _Included_data_scripts_ffmpeg_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_data_scripts_ffmpeg_FFmpeg_init
  (JNIEnv *, jclass);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    openImage
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_data_scripts_ffmpeg_FFmpeg_openImage
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    closeImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_data_scripts_ffmpeg_FFmpeg_closeImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    getImageBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_data_scripts_ffmpeg_FFmpeg_getImageBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    resizeImage
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_data_scripts_ffmpeg_FFmpeg_resizeImage
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    getVideoFps
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_data_scripts_ffmpeg_FFmpeg_getVideoFps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    getDurationSeconds
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_data_scripts_ffmpeg_FFmpeg_getDurationSeconds
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    seek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_data_scripts_ffmpeg_FFmpeg_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    closePipe
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_data_scripts_ffmpeg_FFmpeg_closePipe
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    openPipeNoSound
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_data_scripts_ffmpeg_FFmpeg_openPipeNoSound
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    readFrameNoSound
 * Signature: (J)Ldata/scripts/ffmpeg/VideoFrame;
 */
JNIEXPORT jobject JNICALL Java_data_scripts_ffmpeg_FFmpeg_readFrameNoSound
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    openPipe
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_data_scripts_ffmpeg_FFmpeg_openPipe
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    read
 * Signature: (J)Ldata/scripts/ffmpeg/Frame;
 */
JNIEXPORT jobject JNICALL Java_data_scripts_ffmpeg_FFmpeg_read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    getAudioSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_data_scripts_ffmpeg_FFmpeg_getAudioSampleRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     data_scripts_ffmpeg_FFmpeg
 * Method:    getAudioChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_data_scripts_ffmpeg_FFmpeg_getAudioChannels
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
