/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class videolib_ffmpeg_FFmpeg */

#ifndef _Included_videolib_ffmpeg_FFmpeg
#define _Included_videolib_ffmpeg_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_videolib_ffmpeg_FFmpeg_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    freeBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_videolib_ffmpeg_FFmpeg_freeBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    openImage
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_videolib_ffmpeg_FFmpeg_openImage
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    closeImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_videolib_ffmpeg_FFmpeg_closeImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getImageBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_videolib_ffmpeg_FFmpeg_getImageBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    resizeImage
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_videolib_ffmpeg_FFmpeg_resizeImage
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getVideoFps
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_videolib_ffmpeg_FFmpeg_getVideoFps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getErrorStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_videolib_ffmpeg_FFmpeg_getErrorStatus
(JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getDurationSeconds
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_videolib_ffmpeg_FFmpeg_getDurationSeconds
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getDurationUs
 * Signature: (JL)L
 */
JNIEXPORT jlong JNICALL Java_videolib_ffmpeg_FFmpeg_getDurationUs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    seek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_videolib_ffmpeg_FFmpeg_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    closeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_videolib_ffmpeg_FFmpeg_closeCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    openCtxNoSound
 * Signature: (Ljava/lang/String;IIJ)J
 */
JNIEXPORT jlong JNICALL Java_videolib_ffmpeg_FFmpeg_openCtxNoSound
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    readFrameNoSound
 * Signature: (J)Lvideolib/ffmpeg/VideoFrame;
 */
JNIEXPORT jobject JNICALL Java_videolib_ffmpeg_FFmpeg_readFrameNoSound
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    openCtx
 * Signature: (Ljava/lang/String;IIJ)J
 */
JNIEXPORT jlong JNICALL Java_videolib_ffmpeg_FFmpeg_openCtx
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    read
 * Signature: (J)Lvideolib/ffmpeg/Frame;
 */
JNIEXPORT jobject JNICALL Java_videolib_ffmpeg_FFmpeg_read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getAudioSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_videolib_ffmpeg_FFmpeg_getAudioSampleRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getAudioChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_videolib_ffmpeg_FFmpeg_getAudioChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getWidthAndHeight
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_videolib_ffmpeg_FFmpeg_getWidthAndHeight
  (JNIEnv *, jclass, jstring);


/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    getTotalFrameCount
 * Signature: (J)V
 */
JNIEXPORT jlong JNICALL Java_videolib_ffmpeg_FFmpeg_getTotalFrameCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    isImageRGBA
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_videolib_ffmpeg_FFmpeg_isImageRGBA
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    isRGBA
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_videolib_ffmpeg_FFmpeg_isRGBA
  (JNIEnv *, jclass, jlong);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    fileExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_videolib_ffmpeg_FFmpeg_fileExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     videolib_ffmpeg_FFmpeg
 * Method:    estimateCtxMem
 * Signature: (Ljava/lang/String;IIJ)V
 */
JNIEXPORT jint JNICALL Java_videolib_ffmpeg_FFmpeg_estimateCtxMem
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
