package videolib.entities;

import java.util.Map;

import com.fs.starfarer.api.campaign.LocationAPI;
import com.fs.starfarer.campaign.BaseLocation;
import com.fs.starfarer.campaign.CustomCampaignEntity;

import videolib.entities.CampaignBillboard.BillboardDialogDelegate;
import videolib.entities.CampaignBillboard.BillboardFacingDelegate;
import videolib.playerui.VideoPlayer;
import videolib.projector.AutoTexProjector.AutoTexProjectorAPI;

public class CampaignBillboardFactory {
    /**
     * Adds a CampaignBillboard enttiy to a given Location, functions almost identically to LocationAPI.addCustomEntity. 
     * Use SectorEntityToken.setFixedLocation() or .setCircularOrbit (or setOrbit) to set its location and/or orbit.
     * 
     * @param location                  Location to add the billboard to
     * @param id                        unique id. autogenerated if null.
     * @param name                      default name for entity used if this is null
     * @param type                      id in custom_entities.json
     * @param factionId                 defaults to "neutral" if not specified - by default the color of the billboard projector holo and lens uses the faction's color
     * @return a {@link CampaignBillboard} entity wrapping a {@link CustomCampaignEntity}
     */
    public static CampaignBillboard addCampaignBillboard(
        LocationAPI location,
        String id,
        String name,
        String type,
        String factionId
    ) {
        return new CampaignBillboard((BaseLocation)location, id, name, type, factionId, 0.75f, 1f);
    }

    /**
     * Adds a CampaignBillboard enttiy to a given Location, functions almost identically to LocationAPI.addCustomEntity
     * Use SectorEntityToken.setFixedLocation() or .setCircularOrbit (or setOrbit) to set its location and/or orbit.
     * 
     * @param location                  Location to add the billboard to
     * @param id                        unique id. autogenerated if null.
     * @param name                      default name for entity used if this is null
     * @param type                      id in custom_entities.json
     * @param factionId                 defaults to "neutral" if not specified - by default the color of the billboard projector holo and lens uses the faction's color
     * @param alphaMult                 opacity of the projected texture
     * @param holoLensStructureScale    size scale of the holo platform/lenses
     * @return a {@link CampaignBillboard} entity wrapping a {@link CustomCampaignEntity}
     */
    public static CampaignBillboard addCampaignBillboard(
        LocationAPI location,
        String id,
        String name,
        String type,
        String factionId,
        float alphaMult,
        float holoLensStructureScale
    ) {
        return new CampaignBillboard((BaseLocation)location, id, name, type, factionId, alphaMult, holoLensStructureScale);
    }

    /**
     * Adds a CampaignBillboard enttiy to a given Location, functions almost identically to LocationAPI.addCustomEntity
     * Use SectorEntityToken.setFixedLocation() or .setCircularOrbit (or setOrbit) to set its location and/or orbit.
     * 
     * @param location                  Location to add the billboard to
     * @param id                        unique id. autogenerated if null.
     * @param name                      default name for entity used if this is null
     * @param type                      id in custom_entities.json
     * @param factionId                 defaults to "neutral" if not specified - by default the color of the billboard projector holo and lens uses the faction's color
     * @param alphaMult                 opacity of the projected texture
     * @param holoLensStructureScale    size scale of the holo platform/lenses
     * @param angleDelegate             delegate to get the angle at which the billboard should face per frame. If null then uses the entity's facing angle. See: {@link RotationalTargeter.Default} and {@link RotationalTargeter.PointAtOrbitFocus}
     * @return a {@link CampaignBillboard} entity wrapping a {@link CustomCampaignEntity}
     */
    public static CampaignBillboard addCampaignBillboard(
        LocationAPI location,
        String id,
        String name,
        String type,
        String factionId,
        float alphaMult,
        float holoLensStructureScale,
        BillboardFacingDelegate angleDelegate
    ) {
        return new CampaignBillboard((BaseLocation)location, id, name, type, factionId, alphaMult, holoLensStructureScale, angleDelegate);
    }

    /**
     * Adds a CampaignBillboard enttiy to a given Location, functions almost identically to LocationAPI.addCustomEntity
     * Use SectorEntityToken.setFixedLocation() or .setCircularOrbit (or setOrbit) to set its location and/or orbit.
     * 
     * @param location                  Location to add the billboard to
     * @param id                        unique id. autogenerated if null.
     * @param name                      default name for entity used if this is null
     * @param type                      id in custom_entities.json
     * @param factionId                 defaults to "neutral" if not specified - by default the color of the billboard projector holo and lens uses the faction's color
     * @param spriteWidth               width of the projected texture
     * @param spriteHeight              height of the projected texture
     * @param alphaMult                 opacity of the projected texture
     * @param holoLensStructureScale    size scale of the holo platform/lenses
     * @param angleDelegate             delegate to get the angle at which the billboard should face per frame. If null then uses the entity's facing angle. See: {@link RotationalTargeter.Default} and {@link RotationalTargeter.PointAtOrbitFocus}
     * @param interactionDialogDelegate delegate to execute when the billboard entity is interacted with by the player. If non null and the returned {@link CampaignBillboard} is linked to an {@link AutoTexProjectorAPI} via its texture defined in custom_entites.json then it will strip all options and put a {@link VideoPlayer} in the center of the interaction dialog
     * @return a {@link CampaignBillboard} entity wrapping a {@link CustomCampaignEntity}
     */
    public static CampaignBillboard addCampaignBillboard(
        LocationAPI location,
        String id,
        String name,
        String type,
        String factionId,
        float spriteWidth,
        float spriteHeight,
        float alphaMult,
        float holoLensStructureScale,
        BillboardFacingDelegate angleDelegate,
        BillboardDialogDelegate interactionDialogDelegate
    ) {
        return new CampaignBillboard((BaseLocation)location, id, name, type, factionId, spriteWidth, spriteHeight, alphaMult, holoLensStructureScale, angleDelegate, interactionDialogDelegate);
    }

    /**
     * Adds a CampaignBillboard enttiy to a given Location, functions almost identically to LocationAPI.addCustomEntity
     * Use SectorEntityToken.setFixedLocation() or .setCircularOrbit (or setOrbit) to set its location and/or orbit.
     * 
     * @param location                  Location to add the billboard to
     * @param id                        unique id. autogenerated if null.
     * @param name                      default name for entity used if this is null
     * @param type                      id in custom_entities.json
     * @param factionId                 defaults to "neutral" if not specified - by default the color of the billboard projector holo and lens uses the faction's color
     * @param spriteWidth               width of the projected texture
     * @param spriteHeight              height of the projected texture
     * @param params                    params for the wrapped CustomCampaignEntity
     * @param alphaMult                 opacity of the projected texture
     * @param holoLensStructureScale    size scale of the holo platform/lenses
     * @param angleDelegate             delegate to get the angle at which the billboard should face per frame. If null then uses the entity's facing angle. See: {@link RotationalTargeter.Default} and {@link RotationalTargeter.PointAtOrbitFocus}
     * @param interactionDialogDelegate delegate to execute when the billboard entity is interacted with by the player. If non null and the returned {@link CampaignBillboard} is linked to an {@link AutoTexProjectorAPI} via its texture defined in custom_entites.json then it will strip all options and put a {@link VideoPlayer} in the center of the interaction dialog
     * @return a {@link CampaignBillboard} entity wrapping a {@link CustomCampaignEntity}
     */
    public static CampaignBillboard addCampaignBillboard(
        LocationAPI location,
        String id,
        String name,
        String type,
        String factionId,
        float spriteWidth,
        float spriteHeight,
        CampaignBillboardParams params,
        float alphaMult,
        float holoLensStructureScale,
        BillboardFacingDelegate angleDelegate,
        BillboardDialogDelegate interactionDialogDelegate
    ) {
        return new CampaignBillboard((BaseLocation)location, id, name, type, factionId, spriteWidth, spriteHeight, params, alphaMult, holoLensStructureScale, angleDelegate, interactionDialogDelegate);
    }
}
