name: Build FFmpeg static and JNI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-all.yml
      - ffmpeg-jni/src/ffmpegjni.c
  pull_request:
    paths:
      - .github/workflows/build-all.yml
      - ffmpeg-jni/src/ffmpegjni.c

jobs:
  build-windows:
    name: Windows (MSYS2)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up MSYS2 with MinGW-w64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-crt-git
            mingw-w64-x86_64-winpthreads-git
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-make
            mingw-w64-x86_64-libtasn1
            mingw-w64-x86_64-nasm

      - name: Fetch FFmpeg source
        shell: cmd
        run: |
          dir c:\mingw64