name: Build FFmpeg static and JNI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-all.yml
  pull_request:
    paths:
      - .github/workflows/build-all.yml
      - ffmpeg-jni/src/ffmpegjni.c

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            autoconf automake build-essential pkg-config yasm nasm make git \
            zlib1g-dev libopus-dev libvorbis-dev libogg-dev libdav1d-dev

      - name: Fetch FFmpeg source
        run: |
          git clone --depth=1 https://github.com/FFmpeg/FFmpeg.git ffmpeg-src

      - name: Build FFmpeg (static)
        working-directory: ffmpeg-src
        env:
          PREFIX: ${{ github.workspace }}/ffmpeg-static/linux
        run: |
          ./configure \
            --disable-everything --disable-doc --disable-programs --disable-debug \
            --disable-ffplay --disable-ffprobe \
            --enable-gpl --enable-static --disable-shared \
            --prefix="$PREFIX" \
            --enable-libvorbis --enable-libopus --enable-libdav1d \
            --enable-decoder=h264,hevc,vp8,vp9,mjpeg,png,webp,gif,opus,vorbis,libdav1d \
            --enable-parser=h264,hevc,vp8,vp9,mjpeg,png,webp,gif,aac,mpegaudio \
            --enable-demuxer=matroska,mov,image2,gif \
            --enable-protocol=file \
            --enable-pic --extra-cflags="-fPIC" --extra-cxxflags="-fPIC"
          make -j"$(nproc)"
          make install

      - name: Build JNI bridge (libffmpegjni.so)
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          set -euo pipefail
          SRC=ffmpeg-jni/src/ffmpegjni.c
          OUT_DIR=ffmpeg-jni/bin/linux
          PREFIX=${{ github.workspace }}/ffmpeg-static/linux
          mkdir -p "$OUT_DIR"
          gcc -O2 -DNDEBUG -fPIC \
            $(pkg-config --cflags dav1d) \
            -I"$PREFIX/include" -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" \
            -o "$OUT_DIR/ffmpegjni.so" \
            -Wl,-Bsymbolic -shared -static-libgcc \
            "$SRC" \
            -L"$PREFIX/lib" \
            "$PREFIX/lib/libswscale.a" \
            "$PREFIX/lib/libavformat.a" \
            "$PREFIX/lib/libavcodec.a" \
            "$PREFIX/lib/libavutil.a" \
            "$PREFIX/lib/libswresample.a" \
            $(pkg-config --libs dav1d) \
            -lpthread -ldl -lm -lz

      - name: Upload artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            ffmpeg-static/linux
            ffmpeg-jni/bin/linux/ffmpegjni.so

  build-macos:
    name: macOS
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          architecture: x64
          set-java-home: true

      - name: Install build dependencies
        run: |
          brew update
          brew install nasm yasm opus libvorbis dav1d

      - name: Fetch FFmpeg source
        run: git clone --depth=1 https://github.com/FFmpeg/FFmpeg.git ffmpeg-src
      - name: Build FFmpeg (static)
        working-directory: ffmpeg-src
        env:
          BREW_PREFIX: $(brew --prefix)
          PREFIX: "${GITHUB_WORKSPACE}/ffmpeg-static/mac"
        run: |
          ./configure \
            --disable-everything \
            --disable-doc \
            --disable-programs \
            --disable-debug \
            --disable-ffplay \
            --disable-ffprobe \
            --enable-gpl \
            --enable-static \
            --disable-shared \
            --prefix="$PREFIX" \
            --enable-cross-compile \
            --target-os=darwin \
            --arch=x86_64 \
            --enable-libvorbis \
            --enable-libopus \
            --enable-libdav1d \
            --enable-decoder=h264,hevc,vp8,vp9,mjpeg,png,webp,gif,opus,vorbis,libdav1d \
            --enable-parser=h264,hevc,vp8,vp9,mjpeg,png,webp,gif,aac,mpegaudio \
            --enable-demuxer=matroska,mov,image2,gif \
            --enable-pic \
            --cc="clang" \
            --cxx="clang++" \
            --extra-cflags="-fPIC -arch x86_64" \
            --extra-ldflags="-arch x86_64"

          make -j"$(sysctl -n hw.ncpu)"
          make install

      - name: Debug FFmpeg install
        run: ls -R "${GITHUB_WORKSPACE}/ffmpeg-static/mac/lib"

      - name: Build JNI bridge (ffmpegjni.dylib)
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          SRC: ffmpeg-jni/src/ffmpegjni.c
          OUT_DIR: ffmpeg-jni/bin/mac
          PREFIX: ${{ github.workspace }}/ffmpeg-static/mac
        run: |
          mkdir -p "$OUT_DIR"
          clang -O2 -DNDEBUG -fPIC \
            $(pkg-config --cflags dav1d) \
            -I"$PREFIX/include" \
            -I"$JAVA_HOME/include" \
            -I"$JAVA_HOME/include/darwin" \
            -o "$OUT_DIR/ffmpegjni.dylib" \
            -dynamiclib \
            -Wl,-undefined,error \
            -arch x86_64 \
            -mmacosx-version-min=10.15 \
            "$SRC" \
            -L"$PREFIX/lib" \
            -L"$(pkg-config --variable=libdir dav1d)" \
            "$PREFIX/lib/libswscale.a" \
            "$PREFIX/lib/libavformat.a" \
            "$PREFIX/lib/libavcodec.a" \
            "$PREFIX/lib/libavutil.a" \
            "$PREFIX/lib/libswresample.a" \
            $(pkg-config --libs dav1d) \
            -lpthread \
            -lm \
            -lz \
            -lbz2 \
            -liconv \
            -framework CoreVideo \
            -framework VideoToolbox \
            -framework CoreMedia \
            -framework CoreFoundation

      - name: Upload artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            ffmpeg-static/mac
            ffmpeg-jni/bin/mac/ffmpegjni.dylib
            