name: Build FFmpeg static and JNI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-all.yml
  pull_request:
    paths:
      - .github/workflows/build-all.yml
      - ffmpeg-jni/src/ffmpegjni.c

# permissions:
#   contents: write

jobs:
  # build-linux:
  #   name: Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: temurin
  #         java-version: '17'

  #     - name: Install build dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y --no-install-recommends \
  #         build-essential zlib1g-dev unzip

  #     - name: Build JNI bridge (libffmpegjni.so)
  #       env:
  #         JAVA_HOME: ${{ env.JAVA_HOME }}
  #       run: |
  #         unzip -o ${{ github.workspace }}/ffmpeg-static/linux/ffmpeg-static-linux.zip -d ${{ github.workspace }}/ffmpeg-static/linux
  #         chmod +x ./ffmpeg-jni/src/buildlinux.sh
  #         ./ffmpeg-jni/src/buildlinux.sh

      # - name: Commit and push built binary (Linux)
      #   if: ${{ github.event_name == 'push' }}
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore(ci): update Linux ffmpegjni.so"
      #     file_pattern: ffmpeg-jni/bin/linux/ffmpegjni.so
      #     branch: ${{ github.ref_name }}

  windows-static:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2 manually
        shell: powershell
        run: |
          $msysInstaller = "https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20230728.exe"
          Invoke-WebRequest $msysInstaller -OutFile "$env:TEMP\msys2.exe"
          Start-Process "$env:TEMP\msys2.exe" -ArgumentList "/SILENT /DIR=C:\msys64" -Wait
          echo "MSYS2 installed to C:\msys64"

      - name: Update MSYS2 and install MinGW64 packages
        shell: msys2 {0}
        run: |
          pacman -Syuu --noconfirm
          pacman -S --noconfirm base-devel git mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-bzip2 mingw-w64-x86_64-libiconv mingw-w64-x86_64-zlib mingw-w64-x86_64-crt-git mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-openssl mingw-w64-x86_64-dav1d

      - name: Copy MinGW64 files to native Windows folder
        shell: msys2 {0}
        run: |
          mkdir -p /c/mingw64/lib
          mkdir -p /c/mingw64/include
          cp -r /mingw64/lib/* /c/mingw64/lib/
          cp -r /mingw64/include/* /c/mingw64/include/
          cp -r /mingw64/bin/* /c/mingw64/bin/

      - name: Ensure MinGW64 is on PATH for PowerShell
        shell: powershell
        run: |
          echo "C:\mingw64\bin" >> $env:GITHUB_PATH
          Write-Host "PATH now includes C:\mingw64\bin"

      - name: Verify copied libraries
        shell: powershell
        run: |
          ls C:\mingw64\lib
          ls C:\mingw64\include
          ls C:\mingw64\bin

      # - name: Build JNI bridge (ffmpegjni.dll)
      #   shell: powershell
      #   run: |
      #     Set-Location $env:GITHUB_WORKSPACE
      #     & powershell -ExecutionPolicy Bypass -File .\ffmpeg-jni\src\buildwindows.ps1

      # - name: Commit and push built binary (Windows)
      #   if: ${{ github.event_name == 'push' }}
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore(ci): update Windows ffmpegjni.dll"
      #     file_pattern: ffmpeg-jni/bin/windows/ffmpegjni.dll
      #     branch: ${{ github.ref_name }}